apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: kuard
    version: "2"
  name: kuard
spec:
  replicas: 3 # change this in order to scale up or down
  selector:
    matchLabels:
      app: kuard
      version: "2"
  template: # when desired pod amount does not match current pod amount (lower) the replicaset will create pods based on this template
    metadata:
      labels:
        app: kuard
        version: "2"
    spec:
      containers:
        - name: kuard
          image: "gcr.io/kuar-demo/kuard-amd64:green"
