apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    run: kuard
  name: kuard
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  # We do daily rollouts, limit the revision history to two weeks of
  # releases as we don't expec to roll back beyond that
  revisionHistoryLimit: 14
  selector:
    matchLabels:
      run: kuard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      annotations:
        kubernetes.io/change-cause: "Update back to the blue kuard"
      labels:
        run: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: Always
        name: kuard
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-10-07T10:50:50Z"
    lastUpdateTime: "2023-10-07T10:50:56Z"
    message: ReplicaSet "kuard-645b4bff86" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-07T10:53:31Z"
    lastUpdateTime: "2023-10-07T10:53:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
