apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
      path: "/var/lib/kuard"
    - name: "kuard-data-nfs"
      nfs:
        server: my.nfs.server.local
        path: "/exports"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      volumeMounts:
        - mountPath : "/data"
          name: "kuard-data"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources: # resources requested per container not per pod
        requests: # requested minimum resource
          cpu: "500m" # 0.5 of a core - m is 10^-3
          memory: "120Mi" 
        limits:   # maximum resource that the container would get
          cpu: "1000m" # a core
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP

